export const MOVIES = [
    { title: "The Godfather", genre: "Crime", year: 1972 },
    { title: "The Dark Knight", genre: "Action", year: 2008 },
    { title: "Pulp Fiction", genre: "Crime", year: 1994 },
    { title: "Forrest Gump", genre: "Drama", year: 1994 },
    { title: "Inception", genre: "Sci-Fi", year: 2010 },
    { title: "The Matrix", genre: "Sci-Fi", year: 1999 },
    { title: "Star Wars", genre: "Sci-Fi", year: 1977 },
    { title: "Jurassic Park", genre: "Adventure", year: 1993 },
    { title: "Titanic", genre: "Romance", year: 1997 },
    { title: "The Lion King", genre: "Animation", year: 1994 },
    { title: "Avatar", genre: "Sci-Fi", year: 2009 },
    { title: "Frozen", genre: "Animation", year: 2013 },
    { title: "Jaws", genre: "Thriller", year: 1975 },
    { title: "Harry Potter", genre: "Fantasy", year: 2001 },
    { title: "Back to the Future", genre: "Sci-Fi", year: 1985 },
    { title: "Indiana Jones", genre: "Adventure", year: 1981 },
    { title: "Home Alone", genre: "Comedy", year: 1990 },
    { title: "Die Hard", genre: "Action", year: 1988 },
    { title: "Toy Story", genre: "Animation", year: 1995 },
    { title: "Shrek", genre: "Animation", year: 2001 },
    { title: "Finding Nemo", genre: "Animation", year: 2003 },
    { title: "The Avengers", genre: "Action", year: 2012 },
    { title: "Black Panther", genre: "Action", year: 2018 },
    { title: "Spider-Man", genre: "Action", year: 2002 },
    { title: "Coco", genre: "Animation", year: 2017 },
    { title: "Joker", genre: "Thriller", year: 2019 },
    { title: "Parasite", genre: "Thriller", year: 2019 },
    { title: "Get Out", genre: "Horror", year: 2017 },
    { title: "La La Land", genre: "Musical", year: 2016 },
    { title: "Interstellar", genre: "Sci-Fi", year: 2014 },
    { title: "Gladiator", genre: "Action", year: 2000 },
    { title: "The Terminator", genre: "Sci-Fi", year: 1984 },
    { title: "Rocky", genre: "Sports", year: 1976 },
    { title: "Psycho", genre: "Horror", year: 1960 },
    { title: "The Shining", genre: "Horror", year: 1980 }
];
